#!/bin/sh
libtoolize || exit 1
aclocal || exit 1
autoheader || exit 1
automake --add-missing || exit 1
autoconf || exit 1
#./configure --prefix=/usr --localstatedir=/var --sysconfdir=/etc --libdir=/usr/lib || exit 1
