# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=debug
endif
export config

PROJECTS := Homegear

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

Homegear: 
	@echo "==== Building Homegear ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f Homegear.make

clean:
	@${MAKE} --no-print-directory -C . -f Homegear.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   debug"
	@echo "   release"
	@echo "   profiling"
	@echo "   debug_rpi"
	@echo "   release_rpi"
	@echo "   profiling_rpi"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Homegear"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
