#!/bin/sh

case "$1" in
	remove|abort-install|abort-upgrade)
		# This package is being removed, but its configuration has not yet
		# been purged.

		;;

        purge)
                rm -Rf /etc/homegear > /dev/null 2>&1
                rm -Rf /var/lib/homegear > /dev/null 2>&1
                rm -Rf /var/log/homegear > /dev/null 2>&1
                rm -Rf /var/run/homegear > /dev/null 2>&1
                insserv -rf homegear >/dev/null 2>&1
                rm /etc/init.d/homegear > /dev/null 2>&1
		deluser homegear > /dev/null 2>&1
                ;;

	disappear)
		;;

	upgrade)
		;;

	failed-upgrade)
		;;

	*) echo "$0: didn't understand being called with \`$1'" 1>&2
		exit 1;;
esac

exit 0


