#!/bin/sh

case $1 in
	# Configure this package. If the package must prompt the user for
	# information, do it here.
	configure)
		service homegear start
		RUNNING=0
		INDEX=0
        while [ $RUNNING -eq 0 ] && [ $INDEX -lt 60 ]; do
                sleep 1
                RUNNING=`netstat -nlp 2> /dev/null | grep homegear | grep -c 2001`
                INDEX=$((INDEX+1))
        done
        if [ $RUNNING -eq 0 ]; then
        	echo "Could create OpenWeatherMap device in Homegear. Please create it manually. If Homegear does not listen on it's default port (2001) or if you enabled SSL on port 2001, please modify the file \"/var/lib/homegear/scripts/DeviceScripts/OpenWeatherMap/Connect.php\"."
        	exit 0;
        fi
		/var/lib/homegear/scripts/DeviceScripts/OpenWeatherMap/Setup.php
		rm -f /var/lib/homegear/scripts/DeviceScripts/OpenWeatherMap/Setup.php
		;;

	# Back out of an attempt to upgrade this package FROM THIS VERSION
	# to version $2. Undo the effects of "prerm upgrade $2".
	abort-upgrade)
		service homegear start
		;;

	# Back out of an attempt to remove this package, which was due to
	# a conflict with package $3 (version $4). Undo the effects of
	# "prerm remove in-favour $3 $4".
	abort-remove)
		service homegear start
		;;

	# Back out of an attempt to deconfigure this package, which was
	# due to package $6 (version $7) which we depend on being removed
	# to make way for package $3 (version $4). Undo the effects of
	# "prerm deconfigure in-favour $3 $4 removing $6 $7".
	abort-deconfigure)
		service homegear start
		;;

	*)
		echo "$0: didn't understand being called with \`$1'" 1>&2
		exit 1;
		;;

esac

#DEBHELPER#