#!/bin/sh

case "$1" in
    install)
        ;;

    upgrade|abort-upgrade)
    	service homegear stop
    	rm -f /usr/share/homegear/firmware/GetFirmwareUpdates.sh
    	rm -f /usr/share/homegear/modules/mod_miscellaneous.so
        ;;
esac

#DEBHELPER#

exit 0
