#!/bin/sh
set -e

case "$1" in
    install)
        ;;

    upgrade|abort-upgrade)
    	service homegear stop
    	rm -f /var/lib/homegear/firmware/GetFirmwareUpdates.sh
    	rm -f /var/lib/homegear/modules/mod_*.so
        ;;
esac

#DEBHELPER#

exit 0