#!/bin/sh

### BEGIN INIT INFO
# Provides:		homegear
# Required-Start:	$network $remote_fs $syslog
# Required-Stop:	$network $remote_fs $syslog
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	Start Homegear
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin

. /lib/lsb/init-functions

DAEMON=/usr/bin/homegear
PIDPATH=/var/run/homegear
PIDFILE=$PIDPATH/homegear.pid

test -x $DAEMON || exit 5

if [ -r /etc/default/homegear ]; then
        . /etc/default/homegear
fi

HOMEGEAR_OPTS="$HOMEGEAR_OPTS -d"

LOCKFILE=/var/lock/homegear

lock_homegear() {
        if [ -x /usr/bin/lockfile-create ]; then
                lockfile-create $LOCKFILE
                lockfile-touch $LOCKFILE &
                LOCKTOUCHPID="$!"
        fi
}

unlock_homegear() {
        if [ -x /usr/bin/lockfile-create ] ; then
                kill $LOCKTOUCHPID
                lockfile-remove $LOCKFILE
        fi
}

RUNASUSER=homegear
RUNASGROUP=homegear

case $1 in
        start)
        		if test -e /dev/spidev0.0; then
        			chown root:$RUNASGROUP /dev/spidev0.0
        			chmod 660 /dev/spidev0.0
        		fi

				if test -d /sys/class/gpio; then
					if test ! -d /sys/class/gpio/gpio22; then echo 22 > /sys/class/gpio/export; fi
					echo in > /sys/class/gpio/gpio22/direction
					echo both > /sys/class/gpio/gpio22/edge
					if test ! -d /sys/class/gpio/gpio22; then echo Could not export gpio22; fi
				fi
				
				if test ! -d $PIDPATH; then 
					mkdir $PIDPATH
					chown $RUNASUSER:$RUNASGROUP $PIDPATH
					chmod 750 $PIDPATH
				fi
				
                log_daemon_msg "Starting Homegear" "homegear"
                lock_homegear
                start-stop-daemon --start --quiet --oknodo -c $RUNASUSER -g $RUNASGROUP --pidfile $PIDFILE --startas $DAEMON -- -p $PIDFILE $HOMEGEAR_OPTS
                status=$?
                unlock_homegear
                log_end_msg $status
                ;;
        stop)
                log_daemon_msg "Stopping Homegear" "homegear"
                start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE
                log_end_msg $?
                rm -f $PIDFILE
                ;;
        restart|force-reload)
                $0 stop && sleep 15 && $0 start
                ;;
        try-restart)
                if $0 status >/dev/null; then
                        $0 restart
                else
                        exit 0
                fi
                ;;
        reload)
                exit 3
                ;;
        status)
                status_of_proc $DAEMON "homegear"
                ;;
        *)
                echo "Usage: $0 {start|stop|restart|try-restart|force-reload|status}"
                exit 2
                ;;
esac