#!/bin/sh

### BEGIN INIT INFO
# Provides:		Homegear
# Required-Start:	$network $remote_fs $syslog
# Required-Stop:	$network $remote_fs $syslog
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	Start Homegear
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin

. /lib/lsb/init-functions

DAEMON=/usr/sbin/Homegear
PIDFILE=/var/run/Homegear.pid

test -x $DAEMON || exit 5

if [ -r /etc/default/Homegear ]; then
        . /etc/default/Homegear
fi

HOMEGEAR_OPTS="$HOMEGEAR_OPTS -d"

LOCKFILE=/var/lock/Homegear

lock_homegear() {
        if [ -x /usr/bin/lockfile-create ]; then
                lockfile-create $LOCKFILE
                lockfile-touch $LOCKFILE &
                LOCKTOUCHPID="$!"
        fi
}

unlock_homegear() {
        if [ -x /usr/bin/lockfile-create ] ; then
                kill $LOCKTOUCHPID
                lockfile-remove $LOCKFILE
        fi
}

RUNASUSER=homegear
RUNASGROUP=homegear

case $1 in
        start)
                log_daemon_msg "Starting Homegear" "Homegear"
                lock_homegear
                start-stop-daemon --start --quiet --oknodo -c $RUNASUSER -g $RUNASGROUP --pidfile $PIDFILE --startas $DAEMON -- $HOMEGEAR_OPTS
                status=$?
                unlock_homegear
                log_end_msg $status
                ;;
        stop)
                log_daemon_msg "Stopping Homegear" "Homegear"
                start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE
                log_end_msg $?
                rm -f $PIDFILE
                ;;
        restart|force-reload)
                $0 stop && sleep 2 && $0 start
                ;;
        try-restart)
                if $0 status >/dev/null; then
                        $0 restart
                else
                        exit 0
                fi
                ;;
        reload)
                exit 3
                ;;
        status)
                status_of_proc $DAEMON "Homegear"
                ;;
        *)
                echo "Usage: $0 {start|stop|restart|try-restart|force-reload|status}"
                exit 2
                ;;
esac